require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 200

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Max: 10